### PR TITLE
typescript support

### PR DESCRIPTION
**Pull request by diecodev**
### **I went to the trouble of add typescript support:** 

- I created the types that were needed and added several lines of documentation. 

- I changed the format function that was implemented by another one that is better (because it does not modify the Date.prototype which is a bug in typescript. You can see all the new function in the dateFormat file). 

- I added the EsLint configuration to have a generalized code writing pattern (obtained by Standard style guide because in the files most of them did not have semicolons.

### **To do:** 
- Create the customHook for date handling in the format needed to best carry the component (issue: https://github.com/roto93/react-native-neat-date-picker/issues/17). 
- With the new format function, many things can be done, even changing the timezone, is something I plan to look into as well.
- Make the component more customizable (e.g. add animationIn, animationOut, animationInTiming, animationOutTiming props).

## --STEPS TO PUBLISH THE NEW PACKAGE--
1. git pull origin main (in case you merge the branch, otherwise clone my branch).
2. `npm install --save`.
3. `npx tsc` (in case you have typescript installed as a global deps, use just `tsc`).
4. then, you can tun the npm update command in terminal/bash.

Sorry for add contributors tag in package json (in case you are disagree). 💙

### CODE REVIEW

**Comment by roto93** [comment]
Hi, thank you very much for this typescript support. 
I'm trying to understand what you have done these days but it seems that I don't have adequate knowledge about typescript.

So I think what I'm going to do is just make sure this package can run in RN/Expo projects. Then I'll accept this PR.

Just one thing. Do you think it is a good idea to merge this PR to main and update the original package, or it's better to publish a NEW package something like `react-native-neat-date-picker-ts`?

**Comment by diecodev** [comment]
Hi, roto. Sorry for the late response.

I agree with whatever you decide. But to be honest I think is better (if you are agree, of course) if you made me a moderator or collab to help you with some issues and anything else. I notice about your actual situation (militar situation) and I think that I can help you with issues and making you some PR's just for make the component such better.

**Comment by roto93** [comment]
That would be great! It's very happy to know that you are willing to collaborate this component.
I will send you a collaborater invitation. Thank you.

**Comment by diecodev** [comment]
It's very nice to know you are agree with my request. In 2 weeks I am going to make one other PR with the custom hook I mentined and I going to work in the readme file to update docs (in the typescript branch).


Btw, what do you decide? A create new package or just update this one?

**Comment by roto93** [comment]
I decide to update this one.  That way both JS and TS users can use it, and only one package needs to be maintained.

**Comment by diecodev** [comment]
Oh, that's great. I've been bussy for a little bit, but now I got time to work in some updates. I'm going to wait for the merge to work on it. Blessings.

**Comment by roto93** [comment]
I've done the test of this PR.  time to merge it.  I should have done this earlier😅 
I think I will publish a new version for now and you can working on further works you've mentioned. 
Thanks a lot!

**Pull request merged**
